
name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.2.1

    - name: Download artefato gerado
      uses: actions/download-artifact@v3.0.1
      with:
        # Artifact name
        name: programa em go
      
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        #registry: # optional
        # Username used to log against the Docker registry
        username: maikonigor
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        push: true
        tags: maikonigor/go_ci:${{github.ref_name}}
