# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.19', '1.18', '>=1.19']
        os: ['ubuntu-latest', 'ubuntu-20.04']
    steps:
    - uses: actions/checkout@v3

    - name: echo
      run: echo "${{ secrets.PASSWORD_DOCKER_HUB }}"
    - name: echo2
      run: echo "$PASSWORD_DOCKER_HUB"

    - name: Set up Go ${{ matrix.go_version }} on ${{ matrix.os }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
      
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-20.04']
    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      run: go build -v main.go

  docker:
    needs: build
    # uses: ./.github/workflows/Docker.yml
    # secrets: inherit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        #registry: # optional
        # Username used to log against the Docker registry
        username: maikonigor
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        # Log out from the Docker registry at the end of a job
        logout: true
    
    
